{% set name = "semi-ate-sammy" %}
{% set version = "1.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/semi-ate-sammy-{{ version }}.tar.gz
  sha256: 1545f99b1708cbd87ef24a3334c381106a132df12d39703bcdc769fee9d04842

build:
  number: 0
  noarch: python
  entry_points:
    - sammy=ate_sammy.sammy:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - jinja2
    - python >=3.8
    - semi-ate-project-database
    - semi-ate-common

test:
  imports:
    - ate_sammy
    - ate_sammy.coding
  commands:
    - pip check
    - sammy --help
  requires:
    - pip

about:
  home: https://pypi.org/project/semi-ate-sammy/
  summary: Sammy is a CLI for generating test programs in python
  license: GPL-2.0-only
  license_file: ate_sammy/LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
